apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::286305566135:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1MOSU8BCYPKV1
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::286305566135:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2022-05-31T15:12:38Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "174217"
  uid: f1a6ba7a-1df6-4c0e-a698-20cf05fab82b
